### ISSUE TITLE
ERROR in ubuntu 22.04

### ISSUE THREAD

**Issue by CoveyZhang** [stefanberger/eckey-testing#2]
I find I cannot run the shell successfully. 
```
./test-ecc-kernel-keys.sh 

911660608

Testing with curves:  prime256v1 prime192v1 secp384r1

add_key: No such file or directory

Error: Could not load valid certificate!

curve: prime256v1 hash: sha1
```
I try to change my kernel edition from 5.15 to 6.5 of ubuntu official, besides I try to build by myself, but this problem is still happend.

Did you see this before?

**Comment by CoveyZhang** [comment]
my openssl version is shown as below:
> openssl is already the newest version (3.0.2-0ubuntu1.15).

**Comment by CoveyZhang** [comment]
I found my ecdsa-generic module is not loaded. thanks~

**Comment by stefanberger** [comment]
I updated PR #1 to filter-out curves not supported by the kernel driver. This avoids failing while running the test and instead indicate to the user that curves are not supported by the kernel.
